# R for travis documentation: https://docs.travis-ci.com/user/languages/r
# Activated this repo at https://travis-ci.org/organizations/waldronlab/repositories

# Get rid of the "deploy" section if you don't want to deploy a website to GitHub Pages
# Create a token at https://github.com/settings/tokens ()
# Enter this token as an environment value with name "GITHUB_TOKEN", "available to all branches", at
#      https://travis-ci.org/github/waldronlab/ProjectAsPackage/settings

language: r
r:
  - release
sudo: false
cache: packages

# Strict checks in place
warnings_are_errors: false

# Test code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript --vanilla -e "pkgdown::build_site(lazy=TRUE)"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master