# R for travis documentation: https://docs.travis-ci.com/user/languages/r
# Activated this repo at https://travis-ci.org/organizations/waldronlab/repositories

# Get rid of the "deploy" section if you don't want to deploy a website to GitHub Pages
# Create a token at https://github.com/settings/tokens (for "scopes" choose "repo" and "admin:repo_hook")
# Enter this token as an environment value with name "GITHUB_TOKEN", "available to all branches", on travis-ci.org at
#      https://travis-ci.org/github/waldronlab/ProjectAsPackage/settings

language: r
r:
  - release
cache: packages

# Strict checks in place
warnings_are_errors: false

# Test code coverage
r_github_packages:
  - jimhester/covr

before_cache:
  - Rscript -e 'remotes::install_cran("pkgdown")'

after_success:
  - Rscript -e 'library(covr);codecov()'

deploy:
  provider: pages
  script: Rscript -e 'pkgdown::deploy_site_github()'
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master